"""initial schema

Revision ID: 84e530b3813b
Revises: 
Create Date: 2026-07-21 19:29:22.604550
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '84e530b3813b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('icp', sa.Text(), nullable=True),
    sa.Column('regions', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage_detail', sa.Text(), nullable=True),
    sa.Column('orchestrator_model', sa.String(length=128), nullable=False),
    sa.Column('target_models', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_company_id'), ['company_id'], unique=False)

    op.create_table('questions',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('expected_source_types', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_run_id'), ['run_id'], unique=False)

    op.create_table('reports',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_run_id'), ['run_id'], unique=False)

    op.create_table('model_responses',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('finish_reason', sa.String(length=32), nullable=True),
    sa.Column('web_search_used', sa.Boolean(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_responses_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_responses_run_id'), ['run_id'], unique=False)

    op.create_table('citations',
    sa.Column('response_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('question_index', sa.Integer(), nullable=True),
    sa.Column('brand_owned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['model_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citations_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_citations_response_id'), ['response_id'], unique=False)

    op.create_table('mentions',
    sa.Column('response_id', sa.String(length=36), nullable=False),
    sa.Column('entity', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['model_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentions_response_id'), ['response_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentions_response_id'))

    op.drop_table('mentions')
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citations_response_id'))
        batch_op.drop_index(batch_op.f('ix_citations_domain'))

    op.drop_table('citations')
    with op.batch_alter_table('model_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_responses_run_id'))
        batch_op.drop_index(batch_op.f('ix_model_responses_model_id'))

    op.drop_table('model_responses')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_run_id'))

    op.drop_table('reports')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_run_id'))

    op.drop_table('questions')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_company_id'))

    op.drop_table('runs')
    op.drop_table('companies')
    # ### end Alembic commands ###
